<!doctype html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Cache-Control" content="max-age=0" />
<meta name="MobileOptimized" content="240" />
<meta name="apple-touch-fullscreen" content="yes" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name = "format-detection" content="telephone = no" />
<meta content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no" id="viewport" name="viewport">
<title>全部成分</title>
<link rel="stylesheet"  href="/assets/css/common.css" type="text/css" />
<link rel="stylesheet"  href="/assets/css/style.css" type="text/css" />
</head>
<body>
    <!--头部标题-->
<!--<div class="skinTop">
<a class="leftarrow" href="../index/{{product['product_id']}}?token={{token}}&f=1"><img src="/assets/images/leftarrow.png" width="9" height="17" alt=""/></a>
<h1>全部成分</h1>
<div class="right"><a href="#" id="collect" class="collect {% if collect%} cback_red {%else%}cback_plain{%endif%}" onclick="collect('{{token}}','{{product["product_id"]}}')"></a></div>
</div>-->
    <!--头部标题-->
{% if product %}
<div class="cfCon">
   <div class="cfbox">
       <table width="100%" border="0" cellpadding="0" cellspacing="0" class="cfTable">
         <tbody>  
    <tr>
      <th>成分名称</th>
      <th>功效成分</th>
      <th>易致痘成分</th>
      <th>易致敏成分</th>
      <th style="border:none;">孕哺期慎用</th>
    </tr>   
    {% if (product["components"]  is defined)  and ( product["components"] ) %}
   {% for index,v in product["components"]%}
    <tr>
        {% if index is even%}
            <td> <a href="../element/{{v["component_id"]}}?pid={{product['product_id']}}&token={{token}}">{{v["title"]}}</a></td>
           <td>{% if v['active'] %}<i class="yse">{% endif %}</i></td>
           <td>{% if v['acne_risk'] %}<i class="yse">{% endif %}</i></td>
           <td>{% if v['sensitization'] %}<i class="yse">{% endif %}</td>
           <td>{% if v['safety'] %}<i class="yse">{% endif %}</td>
      {% else %}
            <th> <a href="../element/{{v["component_id"]}}?pid={{product['product_id']}}&token={{token}}">{{v["title"]}}</a></th>
            <th>{% if v['active'] %}<i class="yse">{% endif %}</i></th>
            <th>{% if v['acne_risk'] %}<i class="yse">{% endif %}</i></th>
            <th>{% if v['sensitization'] %}<i class="yse">{% endif %}</i></th>
            <th style="border:none;">{% if v['safety'] %}<i class="yse">{% endif %}</i></th>
      {% endif %}
    </tr> 
    {% endfor %}
    {% endif %}
  </tbody>
</table>

</div>
 {% else%}
    no content
 {% endif %}
 <script src="/assets/js/jquery.min.js"></script>
 <script src="/assets/js/collect.js?v=1.0.3"></script>
</body>
</html>